/* Copyright 2015 The math21 Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================*/

#pragma once

#include "inner.h"
namespace math21 {
    namespace data_structure {
        const std::string text_tinyDG = "13\n"
                           "22\n"
                           " 4  2\n"
                           " 2  3\n"
                           " 3  2\n"
                           " 6  0\n"
                           " 0  1\n"
                           " 2  0\n"
                           "11 12\n"
                           "12  9\n"
                           " 9 10\n"
                           " 9 11\n"
                           " 7  9\n"
                           "10 12\n"
                           "11  4\n"
                           " 4  3\n"
                           " 3  5\n"
                           " 6  8\n"
                           " 8  6\n"
                           " 5  4\n"
                           " 0  5\n"
                           " 6  4\n"
                           " 6  9\n"
                           " 7  6";

        const std::string text_mediumDG = "50\n"
                                          "147\n"
                                          " 0  7\n"
                                          " 0 34\n"
                                          " 1 14\n"
                                          " 1 45\n"
                                          " 1 21\n"
                                          " 1 22\n"
                                          " 1 22\n"
                                          " 1 49\n"
                                          " 2 19\n"
                                          " 2 25\n"
                                          " 2 33\n"
                                          " 3  4\n"
                                          " 3 17\n"
                                          " 3 27\n"
                                          " 3 36\n"
                                          " 3 42\n"
                                          " 4 17\n"
                                          " 4 17\n"
                                          " 4 27\n"
                                          " 5 43\n"
                                          " 6 13\n"
                                          " 6 13\n"
                                          " 6 28\n"
                                          " 6 28\n"
                                          " 7 41\n"
                                          " 7 44\n"
                                          " 8 19\n"
                                          " 8 48\n"
                                          " 9  9\n"
                                          " 9 11\n"
                                          " 9 30\n"
                                          " 9 46\n"
                                          "10  0\n"
                                          "10  7\n"
                                          "10 28\n"
                                          "10 28\n"
                                          "10 28\n"
                                          "10 29\n"
                                          "10 29\n"
                                          "10 34\n"
                                          "10 41\n"
                                          "11 21\n"
                                          "11 30\n"
                                          "12  9\n"
                                          "12 11\n"
                                          "12 21\n"
                                          "12 21\n"
                                          "12 26\n"
                                          "13 22\n"
                                          "13 23\n"
                                          "13 47\n"
                                          "14  8\n"
                                          "14 21\n"
                                          "14 48\n"
                                          "15  8\n"
                                          "15 34\n"
                                          "15 49\n"
                                          "16  9\n"
                                          "17 20\n"
                                          "17 24\n"
                                          "17 38\n"
                                          "18  6\n"
                                          "18 28\n"
                                          "18 32\n"
                                          "18 42\n"
                                          "19 15\n"
                                          "19 40\n"
                                          "20  3\n"
                                          "20 35\n"
                                          "20 38\n"
                                          "20 46\n"
                                          "22  6\n"
                                          "23 11\n"
                                          "23 21\n"
                                          "23 22\n"
                                          "24  4\n"
                                          "24  5\n"
                                          "24 38\n"
                                          "24 43\n"
                                          "25  2\n"
                                          "25 34\n"
                                          "26  9\n"
                                          "26 12\n"
                                          "26 16\n"
                                          "27  5\n"
                                          "27 24\n"
                                          "27 32\n"
                                          "27 31\n"
                                          "27 42\n"
                                          "28 22\n"
                                          "28 29\n"
                                          "28 39\n"
                                          "28 44\n"
                                          "29 22\n"
                                          "29 49\n"
                                          "30 23\n"
                                          "30 37\n"
                                          "31 18\n"
                                          "31 32\n"
                                          "32  5\n"
                                          "32  6\n"
                                          "32 13\n"
                                          "32 37\n"
                                          "32 47\n"
                                          "33  2\n"
                                          "33  8\n"
                                          "33 19\n"
                                          "34  2 \n"
                                          "34 19\n"
                                          "34 40\n"
                                          "35  9\n"
                                          "35 37\n"
                                          "35 46\n"
                                          "36 20\n"
                                          "36 42\n"
                                          "37  5\n"
                                          "37  9\n"
                                          "37 35\n"
                                          "37 47\n"
                                          "37 47\n"
                                          "38 35\n"
                                          "38 37\n"
                                          "38 38\n"
                                          "39 18\n"
                                          "39 42\n"
                                          "40 15\n"
                                          "41 28\n"
                                          "41 44\n"
                                          "42 31\n"
                                          "43 37\n"
                                          "43 38\n"
                                          "44 39\n"
                                          "45  8\n"
                                          "45 14\n"
                                          "45 14\n"
                                          "45 15\n"
                                          "45 49\n"
                                          "46 16\n"
                                          "47 23\n"
                                          "47 30\n"
                                          "48 12\n"
                                          "48 21\n"
                                          "48 33\n"
                                          "48 33\n"
                                          "49 34\n"
                                          "49 22\n"
                                          "49 49";
        }
}